### PR TITLE
README typo => Isolated specs should require unit_helper.rb not spec_helper

### PR DESCRIPTION
**Pull request by jmgarnier**

### CODE REVIEW

**Comment by xaviershay** [comment]
This is the second time I've gotten this pull request, so I guess I need to make the docs clearer :) I'm open to suggestions as to what extra words would help here.

You actually _do_ want to include `spec_helper.rb` here because you are running specs "in the context of your app". Requiring `unit_helper` doesn't make sense because your unit spec will already be requiring it.

This is the whole point of the library: if you run the spec _without_ `spec_helper` it is isolated and fast, and if you run it _with_ `spec_helper` then it verifies that all of your mocks are correct by comparing them to the real thing.

**Comment by jmgarnier** [comment]
Thanks for the clarification Xavier.

I should have read better.

The thing is, I do not want my isolated specs to have the line require_relative "unit_helper" at the top. My unit_helper loads a few testing libs (rspec-fire, ...) which are also loaded by spec_helper.

So I run them with rspec -r ./spec/unit_helper.rb spec/unit/bla_spec.rb

because when they run in the context of the app, spec_helper will already loaded. Maybe you could share an example of unit_helper? Do you have a guard clause which returns if spec_helper has been loaded?

**Comment by xaviershay** [comment]
1. Why don't you want to require unit helper? Requiring some kind of test file is pretty standard.
2. I tended to have a specific helper for each type of test, and either avoid having a spec helper all together, or use it for common things. See http://rhnh.net/2012/12/20/how-i-test-rails-applications
3. Even if your unit helper and your spec helper require the same things, why is that a problem?

I guess I don't understand what you are trying to do, or why it isn't working.

**Comment by myronmarston** [comment]
FWIW, here's how I organize my spec helper stuff, and integrate it w/ rspec fire.
- I have a `spec/spec_helpers` directory with multiple helper files intended for different kinds of specs.
- One file in this directory is `base.rb` -- this does the bare-minimum setup that I want always setup everywhere.  It does things like load setup load paths for my project, load rspec-fire, and set some basic rspec configuration (e.g. filtering options and such).
- The other files in that directory are things like `model_unit.rb` (loaded by isolated model unit tests -- this file, among other things, replaces the Sequel DB adapter with a mock adapter so that all SQL queries are no-ops), `rack_app.rb` (used for testing rack middleware, sinatra apps, etc -- this loads rack-test and adds some additional helper methods that layered on top of that) and `acceptance.rb` (this provides some helper methods for running all pending jobs in my job queue and asserting there were no failures, among other things).
- Each of these files requires `spec_helpers/base` so that the base spec_helper file is _always_ loaded first (which is important because it sets some rspec configuration that needs to be set first).
- In my specs, the first line is always a require of one of these files--whichever is most appropriate for the kind of spec the file is.  Many of my specs require `spec_helpers/base` because they are isolated unit tests that don't have a dependency on anything.  Note that all of my requires are relative to the `spec` directory, since rspec puts this on the load path for you; consistently using this form ensures there are no double-load problems or anything.
- At the command line, I don't need to muck with extra `-r` options to load an appropriate helper file since my specs directly load what they need.

Does that help?

**Comment by fgrehm** [comment]
I'm not sure what you guys think but what I'd also do is set up my "run all specs" task (usually the default rake task) to somehow set up rspec-fire to verify constant names regardless of the test isolation level to make sure any rspec-fire doubled "thing" actually exists.

With this approach I can stay sane and make sure I catch underlying changes to third party doubled classes at early stages :-)

**Comment by myronmarston** [comment]
> I'm not sure what you guys think but what I'd also do is set up my "run all specs" task (usually the default rake task) to somehow set up rspec-fire to verify constant names regardless of the test isolation level to make sure any rspec-fire doubled "thing" actually exists.

You can already do this!  I forget to mention in my description above, but I use this code snippet in my `spec_helper/acceptance.rb` file:

``` ruby
RSpec::Fire.configure do |c|
  c.verify_constant_names = true
end
```

The point of putting it in `spec_helper/acceptance.rb` isn't so much because I intend to use rspec-fire in my acceptance specs...it's because this file is loaded when I run all my specs together (with the full app loaded) so that this causes my constant names to be validated.

**Comment by jmgarnier** [comment]
@myronmarston It helps a LOT! Your explanation is crystal clear.

Thank you.

**Pull request closed without merging**
