### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by myronmarston**
This should fix the travis build.

### CODE REVIEW

**Comment by myronmarston** [comment]
Actually, I just noticed this passes on 1.9.2 but not 1.8.7.  I'm working on a fix, and you should probably hold off merging until then.

**Comment by myronmarston** [comment]
K, that should fix it :).

**Comment by xaviershay** [comment]
I'm still concerned I can't reproduce this. It is hurting my self-confidence.

Thanks, merged.

**Comment by myronmarston** [comment]
Not sure if this is helpful or not, but here's what I did to repro it:

``` bash
$ export BUNDLE_GEMFILE=spec/gemfiles/rspec25
$ bundle install
$ bundle exec rspec spec
```

It occurs to me that it would be fairly easy to run rspec-core 2.6 but actually use a newer version of rspec-mocks.  If you don't use `bundle exec` or an isolated RVM gemset for the rspec-2.6 gems, then when rspec-core runs `require "rspec/mocks"` it will simply load the newest rspec-mocks available, even if it's a different version from rspec core.  So if you did something like `rspec _2.5.2_ spec` to run the specs, that would use version 2.5.2 of the rspec binary, but still use the newest rspec-mocks you have installed.

**Pull request merged**
